version: '3'
services:
  db:
    image: mongo:5.0.8
    container_name: mongo_db
    ports:
      - '27017:27017'
  nodejs-server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    container_name: nodejs-server
    depends_on:
      - db
  react-ui:
    build:
      context: ./client
    ports:
      - "8000:8000"
    container_name: react-ui
    stdin_open: true
    depends_on:
      - nodejs-server
